package com.takeya.FargateTraining.aws.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "sample")
public class SampleEntirty extends CommonItem {

    private String id;
    private String name;

    // TODO 続き パーティションキー・ハッシュキー・インデックス・ソートキーなどの用語理解必須
    @DynamoDBHashKey(attributeName = "id")
//    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

}
